### ISSUE TITLE
Issue with shortcut to Binary file on VM

### ISSUE THREAD

**Issue by saiteja09** [SoftwareEngineeringToolDemos/ICSE-2011-JavAdaptor#5]
When the shortcut to binary is opened on the VM, it's opening the binary jar file with Archive Manager and showing files inside the jar file. Ideally it should open the folder in which the binary is present.

**Comment by sktomer** [comment]
the folder contains numerous eclipse plugins .... finding the tool plugin could become difficult for the viewer ! is that okay ? 
also since the tool is not open source, I did not want to provide a copy of jar file directly on the desktop ...

**Comment by saiteja09** [comment]
@CaptainEmerson Professor, What would be the ideal solution for this?

**Comment by CaptainEmerson** [comment]
If the tool's an Eclipse plugin, the link should be to Eclipse with the tool installed.

**Comment by sktomer** [comment]
the VM has a link to Eclipse launcher (with the plugin installed) at desktop.
